name: DestinyTools
version: '${version}'
main: me.srdqrk.destinytools.DestinyTools
api-version: 1.19
permissions:
  destinytools.executer:
    description: Permiso para ejecutar comandos. Permiso solo para staffs
    default: op